Map<String, String> translateArabic = {
  "title": "Usteps",
  "logout": "تسجيل خروج",
  "please_wait": " الرجاء الانتظار ...",
  "sign_in": "تسجيل دخول",
  "email": "البريد الإلكتروني",
  "email_error": "البريد الإلكتروني خاطئ",
  "enter_email": "أدخل البريد الاكتروني",
  "password": "كلمة المرور",
  "enter_password": "أدخل كلمة المرور",
  "welcome_back": "أهلا بعودتك",
  "forgot_password": "نسيت كلمة المرور؟",
  "use_password": "استخدام كلمة المرور",
  "notifications": "الإشعارات", 
  "error_connect_to_netwotk": "لا يوجد اتصال بالانترنت",
  "error_connect_to_server": "مشكله في الاتصال بالسيرفر",
  "new_password": "كلمة المرور الجديدة", 
  "save_changed": "حفظ التغيرات", 
  "identification_number_location":"رقم الهوية / الاقامة",
  "enter_identification_number_location":"أدخل رقم الهوية / الاقامة",
  "episode_list":"قائمة الحلقات",
  "maknoon":"مكنون",
  "synchronization":"مزامنة البيانات",
  "suggestions_and_complaints":"المقترحات و الشكاوي",
  "about_as":"من نحن",
  "submit": "ارسال",
  "draft":"حاضر",
  "done":"اكمل",
  "follow_up":"المتابعة",
  "listen":"الحفظ",
  "reviewsmall":"المراجعة الصغرى",
  "reviewbig":"المراجعة الكبرى",
  "tlawa":"التلاوة",
  "quran":"المصحف",
  "from_sura":"من سورة",
  "from_aya":"من آية",
  "to_sura":"إلى سورة",
  "to_aya":"إلى آية",
  "course":"المقرر",
  "Notes":"الملاحظات",
  "save_errors":"أخطاء الحفظ",
  "preservation_quality":"جودة الحفظ",
  "intonation_errors":"أخطاء التجويد",
  "date_planned":"تاريخ الأستحقاق",
  "actual_date":"تاريخ التسليم",
  "difference_date":"الفرق",
  "day":"يوم",
  "enter_number":"ادخل الرقم",
  "save":"حفظ",
  "can_not_yong_surh":"لا يمكن اختيار سورة ترتيبها أسفل",
  "can_not_up_surh":"لا يمكن اختيار سورة ترتيبها أعلى",
  "can_not_bottom_aya":"لا يمكن اختيار اية ترتيبها أسفل",
  "can_not_up_aya":"لا يمكن اختيار اية ترتيبها أعلى",
  "warring":"تنبيه",
  "ok_add_listen_line":"تم حفظ البيانات بنجاح",
  "error_add_listen_line":"هناك مشكلة في إضافة مقرر",
  "behaviour":"السلوك",
  "behaviour_student":"إضافة سلوك للطالب",
  "note_behaviour_student":"ملاحظات السلوك السابقة",
  "select_behaviour":"اختر سلوك",
  "do_you_want_to_send_the_behavior":"هل تريد إرسال السلوك",
  "inform_the_parent_of_the_behavior":"ابلاغ ولي الامر بالسلوك",
  "send_the_behavior_to_the_episode_moderator":"إرسال السلوك لمشرف الحلقة",
  "yes":"نعم",
  "no":"لا",
  "confirm":"تاكيد",
  "ok_add_behavior":"تم إضافة السلوك بنجاح",
  "error_add_behavior":"هناك مشكلة في إضافة سلوك",
  "there_is_no_notes":"لاتوجد ملاحظات",
  "there_is_no_notifications":"لاتوجد اشعارات",
  "notification_details":"تفاصيل الاشعار",
  "notification_date":"تاريخ الاشعار",
  "ok":"موافق",
  "subject_of_complaint":"موضوع الشكوى",
  "complaint_details":"تفاصيل الشكوى",
  "enter_subject":"ادخل موضوع الشكوى",
  "enter_details":"ادخل تفاصيل الشكوى",
  "studentـnomination":"ترشيح طالب",
  "select_period":"اختر فتره",
  "select_center":"اختر مركز",
  "there_is_no_calendarCenter":"لا توجد جداول للاختبارات",
  "center_test":"مركز الاختبار",
  "type":"النوع",
  "path":"المسار",
  "branch":"الفرع",
  "error_get_branches":"هناك مشكلة في تحميل الفروع",
  "registration":"تسجيل",
  "unregister":"إلغاء تسجيل",
  "ok_registration":"تم التسجيل بنجاح",
  "ok_unregister":"تم إلغاء التسجيل بنجاح",
  "error_registration":"هناك مشكلة في التسجيل",
  "error_unregister":"هناك مشكلة في إلغاء التسجيل",
  "do_you_want_to_logout":"هل تريد تسجيل الخروج",
  "present":"حاضر",
  "absent":"غائب",
  "absent_excuse":"غائب بعذر",
  "not_read":"لم يسمع",
  "excuse":"استأذن",
  "error_set_attendance":"هناك مشكلة ما",
  "date":"التاريخ",
  "there_is_no":"لا يوجد",
  "reset_password":"إعادة تعيين كلمة المرور",
  "complete_the_selection_of_the_course_first_to_display_it_in_the_quran":"أكمل اختيار المقرر أولاً لعرضه في المصحف",
  "your_new_password_ok":"تم إرسال كلمة المرور الجديدة إليك في رسالة نصيّة!",
  "agree":"الموافق",
  "episode_type":"نوع البرنامج",
  "episode_works":"البرنامج",
  "delay":"متأخر",
  "excellent" : "ممتاز",
  "very_good" : "جيد جد",
  "good" : "جيد",
  "accepted" : "مقبول",
  "weak" : "ضعيف",
  "general_behavior" : "السلوك العام للطالب",
  "activate_offline_work_and_data_synchronization" : "تفعيل العمل دون اتصال\nومزامنة البيانات",
  "activate":"تفعيل", 
  "initializing_loading_data":"جاري تهيئة وتحميل البيانات",
  "episodes_and_students":"الحلقات والطلاب",
  "student_courses":"مقررات الطلاب",
  "educational_plan":"التقارير",
  "all_data_will_be_updated_and_all_unreleased_operations_will_be_cancelled":"سوف يتم تحديث كامل البيانات والغاء كل العمليات الغير مرفوعة",
  "student_preparation":"تحضير الطالب",
  "uploadable_data_to_the_server":"البيانات القابلة للرفع الى السيرفر",
  "prepare_students":"تحضير الطلاب",
  "item":"عنصر", 
  "general_behavior_students":"السلوك العام للطلاب", 
  "behaviors_students":"سلوكيات الطلاب",
  "upload_data":"رفع البيانات",
  "there_are_no_changes_to_upload_to_the_server":"لاتوجد تغيرات لرفعها الى السيرفر",
  "do_you_want_to_deactivate_the_offline_work_and_cancel_all_unreleased_operations":"هل تريد إلغاء تفعيل العمل دون اتصال والغاء كل العمليات الغير مرفوعة",
  "upload_data_to_the_server":"جاري رفع التغيرات",
  "changes_uploaded_successfully":"تم رفع التغيرات بنجاح",
  "failed_to_upload_changes":"فشل رفع التغيرات",
  "there_are_no_episodes_please_add_one_episode":"لا توجد حلقات الرجاء إضافة حلقة واحدة",
  "episode_data_is_being_updated":"تم تحديث بيانات الحلقات في النظام.\n الرجاء الضغط على ( مزامنة ) لعكس التحديثات في التطبيق.",
  "student_episode_data_is_being_updated":"تم تحديث بيانات الطلاب في النظام.\n الرجاء الضغط على ( مزامنة ) لعكس التحديثات في التطبيق.",
  "sync":"مزامنة",
};  
  
 
   
   
